spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 666222
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq01
    password: 666222
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password: 666222
